### ISSUE TITLE
Neutral Items : smoke bomb

### ISSUE THREAD

**Issue by atrolla** [atrolla/mmmmmma#18]
a smoke bomb within x radius and y duration.

**Comment by ghost** [comment]
Smoke bomb is only for bomber ?

**Comment by ghost** [comment]
radius:int ?
duration:int ?

**Comment by atrolla** [comment]
you must first start https://github.com/atrolla/mmmmmma/issues/6
radius : double (every coordinates type are double)
duration : int (time is in "tick" = int)

**Comment by ghost** [comment]
thx

**Comment by atrolla** [comment]
Canceled for now.
