### ISSUE TITLE
files in package org.atrolla.game.engine must be moved somewhere else

### ISSUE THREAD

**Issue by atrolla** [atrolla/mmmmmma#22]
package name has no meaning, and is composed of not related classes, enums....

**Comment by ghost** [comment]
quid "package org.atrolla.game.game;" ???

**Comment by atrolla** [comment]
done in 827e00a485d54ed625aab688e3037e3ef483a8d6
base package name is org.atrolla.games (because we will not create only one game :squirrel:)

**Comment by ghost** [comment]
quid "package org.atrolla.games.game;" ???
