### ISSUE TITLE
RoundTests.botIsNotStuckOnBounds randomly fails...

### ISSUE THREAD

**Issue by atrolla** [atrolla/mmmmmma#24]
Thoses related to coordinates 
RandomUtils.buildValidDirectionList does not use hitbox...

**Comment by TheCopycat** [comment]
supposedly corrected

**Comment by atrolla** [comment]
sorry but 59f882d8ae0e2756eb94ac1966af25e42d9e7057 did not fixed it :panda_face:

**Comment by atrolla** [comment]
fixed ? e2672d69bb2d67e9ae5124feda9d0f3b31049791

**Comment by atrolla** [comment]
Managed to reproduce it ...

**Comment by TheCopycat** [comment]
Replaced List<Command>(characterNumber) by List<Command>(botNumber) and fixed everything related.
The tests seems to be ok. Didn't manage to reproduce the bug. I leave open for a week. If the bug is not encountered, I will close it.

**Comment by atrolla** [comment]
fixed in fc88e00b1e68e9c7896d9a0b0bb21e8b759103a7
