### ISSUE TITLE
neutral items bug : player can use it multiple times by spamming use action

### ISSUE THREAD

**Issue by atrolla** [atrolla/mmmmmma#40]
for debug :
- ConfigurationConstants -> spawns faster
- NeutralItemManager -> only locator
- InputManager#updatePlayers

**Comment by TheCopycat** [comment]
When the player is on the locator and uses it, it is repicked at the same frame, since the item is not already gone. The player can then repress the action button to trigger the effect.

The effect is only on locator, since the other neutral item teleports the player.
